/* kiba_install_finish.c — configs, user account, bootloader, finalize.
 * See kiba_install.h for design rationale. */
#define _GNU_SOURCE
#include "kiba_install.h"
#include "kiba_udev.h"

#include <errno.h>
#include <fcntl.h>
#include <spawn.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <dirent.h>
#include <sys/stat.h>
#include <sys/utsname.h>
#include <sys/wait.h>
#include <unistd.h>

extern char **environ;

extern char kiba_install_shared_err[256];
#define g_finish_err kiba_install_shared_err

static int run_argv(char *const argv[]) {
    pid_t pid;
    int rc = posix_spawnp(&pid, argv[0], NULL, NULL, argv, environ);
    if (rc != 0) {
        snprintf(g_finish_err, sizeof(g_finish_err), "failed to spawn %s: %s", argv[0], strerror(rc));
        return -1;
    }
    int status = 0;
    if (waitpid(pid, &status, 0) < 0) {
        snprintf(g_finish_err, sizeof(g_finish_err), "waitpid failed for %s: %s", argv[0], strerror(errno));
        return -1;
    }
    if (WIFEXITED(status) && WEXITSTATUS(status) == 0) return 0;
    if (WIFEXITED(status)) {
        snprintf(g_finish_err, sizeof(g_finish_err), "%s exited with status %d", argv[0], WEXITSTATUS(status));
    } else {
        snprintf(g_finish_err, sizeof(g_finish_err), "%s terminated abnormally", argv[0]);
    }
    return -1;
}

/* Like run_argv, but writes `stdin_data` to the child's stdin before
 * closing it -- used for `chpasswd`, so the password never appears in
 * argv (visible in /proc/PID/cmdline to other users) or in a shell
 * string anywhere. */
static int run_argv_with_stdin(char *const argv[], const char *stdin_data) {
    int pipefd[2];
    if (pipe(pipefd) != 0) {
        snprintf(g_finish_err, sizeof(g_finish_err), "pipe() failed: %s", strerror(errno));
        return -1;
    }

    posix_spawn_file_actions_t actions;
    posix_spawn_file_actions_init(&actions);
    posix_spawn_file_actions_adddup2(&actions, pipefd[0], STDIN_FILENO);
    posix_spawn_file_actions_addclose(&actions, pipefd[1]);

    pid_t pid;
    int rc = posix_spawnp(&pid, argv[0], &actions, NULL, argv, environ);
    posix_spawn_file_actions_destroy(&actions);
    close(pipefd[0]);

    if (rc != 0) {
        close(pipefd[1]);
        snprintf(g_finish_err, sizeof(g_finish_err), "failed to spawn %s: %s", argv[0], strerror(rc));
        return -1;
    }

    size_t len = strlen(stdin_data);
    size_t written = 0;
    while (written < len) {
        ssize_t w = write(pipefd[1], stdin_data + written, len - written);
        if (w < 0) { if (errno == EINTR) continue; break; }
        written += (size_t)w;
    }
    close(pipefd[1]);

    int status = 0;
    waitpid(pid, &status, 0);
    if (WIFEXITED(status) && WEXITSTATUS(status) == 0) return 0;
    snprintf(g_finish_err, sizeof(g_finish_err), "%s failed (chpasswd)", argv[0]);
    return -1;
}

static int chroot_run(const char *target_root, char *const inner_argv[]) {
    /* arch-chroot target_root <inner_argv...> */
    char *argv[16];
    int i = 0;
    argv[i++] = (char *)"arch-chroot";
    argv[i++] = (char *)target_root;
    for (int j = 0; inner_argv[j] != NULL && i < 14; j++) argv[i++] = inner_argv[j];
    argv[i] = NULL;
    return run_argv(argv);
}

static int write_file(const char *path, const char *content) {
    int fd = open(path, O_WRONLY | O_CREAT | O_TRUNC, 0644);
    if (fd < 0) {
        snprintf(g_finish_err, sizeof(g_finish_err), "open(%s) failed: %s", path, strerror(errno));
        return -1;
    }
    size_t len = strlen(content);
    ssize_t w = write(fd, content, len);
    close(fd);
    if (w != (ssize_t)len) {
        snprintf(g_finish_err, sizeof(g_finish_err), "write(%s) failed: %s", path, strerror(errno));
        return -1;
    }
    return 0;
}

int kiba_install_write_configs(const char *target_root,
                                const char *root_uuid, const char *esp_uuid,
                                const char *hostname, const char *locale,
                                const char *keymap) {
    char path[1024];
    char content[2048];

    snprintf(path, sizeof(path), "%s/etc/fstab", target_root);
    snprintf(content, sizeof(content),
              "# KibaOS fstab — generated by installer\n"
              "UUID=%s  /      ext4  defaults,noatime  0 1\n"
              "UUID=%s  /boot  vfat  umask=0077        0 2\n",
              root_uuid, esp_uuid);
    if (write_file(path, content) != 0) return -1;

    snprintf(path, sizeof(path), "%s/etc/hostname", target_root);
    snprintf(content, sizeof(content), "%s\n", hostname);
    if (write_file(path, content) != 0) return -1;

    snprintf(path, sizeof(path), "%s/etc/hosts", target_root);
    snprintf(content, sizeof(content),
              "127.0.0.1   localhost\n"
              "::1         localhost\n"
              "127.0.1.1   %s.localdomain %s\n",
              hostname, hostname);
    if (write_file(path, content) != 0) return -1;

    /* locale.gen: enable the requested locale line, plain text edit. */
    snprintf(path, sizeof(path), "%s/etc/locale.gen", target_root);
    {
        FILE *f = fopen(path, "r");
        if (f) {
            fseek(f, 0, SEEK_END);
            long sz = ftell(f);
            fseek(f, 0, SEEK_SET);
            char *buf = malloc((size_t)sz + 1);
            if (buf) {
                size_t got = fread(buf, 1, (size_t)sz, f);
                buf[got] = 0;
                fclose(f);

                char needle[300];
                snprintf(needle, sizeof(needle), "#%s", locale);
                char *pos = strstr(buf, needle);
                if (pos) memmove(pos, pos + 1, strlen(pos + 1) + 1); /* drop the leading '#' */

                FILE *fw = fopen(path, "w");
                if (fw) { fwrite(buf, 1, strlen(buf), fw); fclose(fw); }
                free(buf);
            }
            /* f already closed above on the success path */
        }
        /* fopen() failed: f is NULL here, nothing to close */
    }

    snprintf(path, sizeof(path), "%s/etc/locale.conf", target_root);
    snprintf(content, sizeof(content), "LANG=%s\n", locale);
    if (write_file(path, content) != 0) return -1;

    snprintf(path, sizeof(path), "%s/etc/vconsole.conf", target_root);
    snprintf(content, sizeof(content), "KEYMAP=%s\n", keymap);
    if (write_file(path, content) != 0) return -1;

    return 0;
}

int kiba_install_locale_gen(const char *target_root) {
    char *argv[] = { (char *)"locale-gen", NULL };
    if (chroot_run(target_root, argv) != 0) {
        snprintf(g_finish_err, sizeof(g_finish_err), "locale-gen failed");
        return -1;
    }
    return 0;
}

int kiba_install_create_user(const char *target_root, const char *username,
                              const char *password) {
    /* The build-time /etc/gdm/custom.conf (customize_airootfs.sh) ships an
     * [daemon] block with AutomaticLoginEnable=true / AutomaticLogin=liveuser
     * -- right for the live session, but an installed system should come up
     * at a normal password prompt, not autologin straight into whichever
     * account the installer just created. This used to swap
     * "AutomaticLogin=liveuser" to the new username in place, which just
     * moved the autologin target instead of removing it (and, before that
     * fix existed, left GDM trying to autologin a liveuser account that
     * userdel below had already removed -- the installed system would come
     * up with no desktop at all).
     * That same [daemon] block also carries WaylandEnable=true, which is
     * what gets GDM to actually offer/launch the KWin Wayland session
     * instead of falling back to Xorg -- deleting custom.conf outright
     * would silently take that with it too. So strip just the two
     * autologin keys, in place, and leave everything else in the file
     * (WaylandEnable=true, and any key a future build-time change adds
     * here) untouched. */
    char path[1024];
    snprintf(path, sizeof(path), "%s/etc/gdm/custom.conf", target_root);
    {
        FILE *f = fopen(path, "r");
        if (f) {
            fseek(f, 0, SEEK_END);
            long sz = ftell(f);
            fseek(f, 0, SEEK_SET);
            char *buf = malloc((size_t)sz + 1);
            if (buf) {
                size_t got = fread(buf, 1, (size_t)sz, f);
                buf[got] = 0;
                fclose(f);

                static const char *const strip_lines[] = {
                    "AutomaticLoginEnable=true\n",
                    "AutomaticLogin=liveuser\n",
                };
                for (size_t si = 0; si < sizeof(strip_lines) / sizeof(strip_lines[0]); si++) {
                    char *pos = strstr(buf, strip_lines[si]);
                    if (pos) {
                        size_t line_len = strlen(strip_lines[si]);
                        memmove(pos, pos + line_len, strlen(pos + line_len) + 1);
                    }
                }

                FILE *fw = fopen(path, "w");
                if (fw) { fwrite(buf, 1, strlen(buf), fw); fclose(fw); }
                free(buf);
            }
            /* f already closed above on the success path */
        }
        /* fopen() failed: f is NULL here, nothing to close */
    }

    /* GDM has no LightDM-style "autologin-session" key -- it just
     * autologins into whatever session AccountsService says is that
     * user's default, falling back to the desktop's listed default
     * session if nothing is set. liveuser gets that default for free
     * (there's only one session installed most of the time), but write
     * it explicitly for the real account too so it's never ambiguous. */
    {
        char accts_dir[1024];
        snprintf(accts_dir, sizeof(accts_dir), "%s/var/lib/AccountsService/users", target_root);
        mkdir(accts_dir, 0755); /* best-effort; may already exist */

        char accts_path[1024];
        snprintf(accts_path, sizeof(accts_path), "%s/%s", accts_dir, username);
        char accts_content[256];
        snprintf(accts_content, sizeof(accts_content),
                 "[User]\nSession=budgie-desktop-kwinwayland\nXSession=budgie-desktop-kwinwayland\nSystemAccount=false\n");
        write_file(accts_path, accts_content); /* best-effort */
    }

    /* Remove the live user -- best effort, ignore failure if absent. */
    {
        char *argv[] = { (char *)"userdel", (char *)"-r", (char *)"liveuser", NULL };
        chroot_run(target_root, argv); /* ignore result intentionally */
    }

    /* Only request supplementary groups that actually exist in the target
     * root's /etc/group. useradd fails its ENTIRE invocation -- creating
     * no user at all -- if even one -G group is missing, and `docker` is
     * exactly that case by design: its group isn't meant to exist until
     * after setup (created once systemd-sysusers actually runs against
     * the installed system, not the image-capture snapshot), so trying
     * to add it here at useradd time was never going to work. That
     * failure used to get silently swallowed, so the account was never
     * created at all, and the *next* step (chpasswd) failed instead with
     * no indication the real problem was upstream. Filtering to groups
     * that are confirmed present -- and separately remembering which
     * ones got deferred, so a first-boot step can add them once they
     * actually exist -- replaces the useradd crash with a proper
     * catch-up instead of just permanently dropping `docker` membership. */
    {
        static const char *const candidate_groups[] = {
            "wheel", "audio", "video", "input", "network",
            "storage", "power", "docker"
        };
        char group_list[256] = "";
        char skipped_list[256] = "";
        char group_line[128];
        for (size_t gi = 0; gi < sizeof(candidate_groups) / sizeof(candidate_groups[0]); gi++) {
            char group_path[1024];
            snprintf(group_path, sizeof(group_path), "%s/etc/group", target_root);
            FILE *gf = fopen(group_path, "r");
            bool found = false;
            if (gf) {
                snprintf(group_line, sizeof(group_line), "%s:", candidate_groups[gi]);
                size_t prefix_len = strlen(group_line);
                char line[256];
                while (fgets(line, sizeof(line), gf)) {
                    if (strncmp(line, group_line, prefix_len) == 0) { found = true; break; }
                }
                fclose(gf);
            }
            if (found) {
                if (group_list[0] != '\0') strncat(group_list, ",", sizeof(group_list) - strlen(group_list) - 1);
                strncat(group_list, candidate_groups[gi], sizeof(group_list) - strlen(group_list) - 1);
            } else {
                if (skipped_list[0] != '\0') strncat(skipped_list, ",", sizeof(skipped_list) - strlen(skipped_list) - 1);
                strncat(skipped_list, candidate_groups[gi], sizeof(skipped_list) - strlen(skipped_list) - 1);
                /* Expected, not exceptional -- docker's group isn't meant
                 * to exist until first boot, so no warning here. The
                 * marker file below is how the first-boot service finds
                 * out, not a log message. */
            }
        }

        char *argv[] = {
            (char *)"useradd", (char *)"-m",
            (char *)"-G", group_list,
            (char *)"-s", (char *)"/bin/bash",
            (char *)username, NULL
        };

        /* Idempotent: if a prior install attempt got this far before
         * failing later on, the user may already exist in target root's
         * /etc/passwd. That's fine -- skip useradd rather than erroring,
         * same intent as the old "tolerate already exists" comment, but
         * checked explicitly instead of swallowing every possible
         * useradd failure (including real ones) to get there. */
        char passwd_path[1024];
        snprintf(passwd_path, sizeof(passwd_path), "%s/etc/passwd", target_root);
        bool user_exists = false;
        FILE *pf = fopen(passwd_path, "r");
        if (pf) {
            char uline[256];
            char prefix[128];
            snprintf(prefix, sizeof(prefix), "%s:", username);
            size_t prefix_len = strlen(prefix);
            while (fgets(uline, sizeof(uline), pf)) {
                if (strncmp(uline, prefix, prefix_len) == 0) { user_exists = true; break; }
            }
            fclose(pf);
        }

        if (!user_exists && chroot_run(target_root, argv) != 0) {
            snprintf(g_finish_err, sizeof(g_finish_err), "useradd failed for %s", username);
            return -1;
        }

        /* Hand off any deferred groups (docker, etc.) to a first-boot
         * service -- writes "username:group1,group2" so it knows who to
         * catch up and with what, once those groups actually exist. */
        if (skipped_list[0] != '\0') {
            char kibaos_dir[1024];
            snprintf(kibaos_dir, sizeof(kibaos_dir), "%s/etc/kibaos", target_root);
            mkdir(kibaos_dir, 0755); /* fine if it already exists */
            char marker_path[1024];
            snprintf(marker_path, sizeof(marker_path), "%s/pending-user-groups", kibaos_dir);
            FILE *mf = fopen(marker_path, "w");
            if (mf) {
                fprintf(mf, "%s:%s\n", username, skipped_list);
                fclose(mf);
            }
        }
    }

    {
        char stdin_data[512];
        snprintf(stdin_data, sizeof(stdin_data), "%s:%s\n", username, password);
        char *argv[] = { (char *)"arch-chroot", (char *)target_root, (char *)"chpasswd", NULL };
        if (run_argv_with_stdin(argv, stdin_data) != 0) {
            snprintf(g_finish_err, sizeof(g_finish_err), "chpasswd failed");
            return -1;
        }
    }

    /* Stash the plaintext account password briefly, root-only, so the
     * WinApps first-login setup (see WINDOWS APP SUPPORT further down)
     * can reuse it as the Windows guest's login too, instead of a random
     * string the person is never shown and can't log in with. This is
     * the only point in the whole install where the password exists in
     * plaintext outside of chpasswd's own stdin pipe, so it's written
     * here and nowhere else. kibaos-winapps-setup reads it exactly once
     * (via pkexec, since it's 0600 root:root) and deletes it immediately
     * after, so it never outlives the single setup step it exists for. */
    {
        char kibaos_dir[1024];
        snprintf(kibaos_dir, sizeof(kibaos_dir), "%s/etc/kibaos", target_root);
        mkdir(kibaos_dir, 0755); /* fine if it already exists */
        char pass_path[1024];
        snprintf(pass_path, sizeof(pass_path), "%s/winapps-userpass", kibaos_dir);
        int fd = open(pass_path, O_WRONLY | O_CREAT | O_TRUNC, 0600);
        if (fd >= 0) {
            ssize_t len = (ssize_t)strlen(password);
            ssize_t written = 0;
            while (written < len) {
                ssize_t w = write(fd, password + written, (size_t)(len - written));
                if (w < 0) { if (errno == EINTR) continue; break; }
                written += w;
            }
            close(fd);
        }
        /* Not fatal if this failed to write -- kibaos-winapps-setup
         * falls back to asking the person for their password directly
         * if the stash file isn't there. */
    }

    /* Pre-create ~/.local/bin, owned by the new account, on the just-
     * installed target -- not the live session. WinApps' setup.sh --user
     * (run later at first login, see kibaos-winapps-firstrun) installs
     * the `winapps` binary itself by `cp`/`tee`-ing straight into
     * ~/.local/bin, and neither of those commands create missing parent
     * directories -- a bare install onto a fresh useradd -m home (which
     * has no .local at all yet) fails outright with e.g. "cp: cannot
     * create regular file '/home/user/.local/bin/winapps': No such file
     * or directory", a documented failure mode upstream. useradd -m
     * populates skel but never creates .local/bin, so this closes that
     * gap once, here, rather than depending on WinApps' installer to
     * handle its own missing directory (best-effort: a failure here
     * shouldn't fail the whole install over a directory WinApps can
     * still create for itself in the common case). */
    {
        char local_bin[1024];
        snprintf(local_bin, sizeof(local_bin), "/home/%s/.local/bin", username);
        char *mkdir_argv[] = {
            (char *)"install", (char *)"-d", (char *)"-m", (char *)"755",
            (char *)"-o", (char *)username, (char *)"-g", (char *)username,
            local_bin, NULL
        };
        chroot_run(target_root, mkdir_argv); /* best-effort, see comment above */
    }

    return 0;
}

int kiba_install_finalize(const char *target_root, const char *disk_path,
                           const char *root_part, const char *root_uuid,
                           int root_partno, bool dualboot,
                           kiba_progress_cb cb, void *user_data) {
    char path[1024];

    if (cb) cb(80, "Cleaning up installer files...", user_data);

    /* io.kibaos.winapps-setup and kibaos-winapps-setup are deliberately
     * NOT in this list, even though io.kibaos.winapps-setup is built
     * alongside io.kibaos.oobe in the same meson project (see WINDOWS APP
     * SUPPORT further down) -- unlike OOBE, that app is meant to still be
     * launchable from the app menu long after install, so its binary
     * (usr/bin/io.kibaos.winapps-setup) and its backend
     * (usr/local/bin/kibaos-winapps-setup) both have to survive this
     * cleanup. Only usr/share/kibaos-oobe -- the vala source tree, needed
     * at build time only -- gets removed. */
    static const char *live_only[] = {
        "usr/share/applications/kibaos-install.desktop",
        "usr/bin/io.kibaos.oobe",
        "usr/share/kibaos-oobe",
        "usr/local/bin/kibaos-oobe-backend",
        "usr/local/bin/kibaos-oem-finish.sh",
        "etc/systemd/system/choose-mirror.service",
        "usr/share/libalpm/hooks/Installation_guide.hook",
        "root/customize_airootfs.sh",
        "root/install.txt",
        "etc/motd",
        "etc/issue",
    };
    for (size_t i = 0; i < sizeof(live_only)/sizeof(live_only[0]); i++) {
        snprintf(path, sizeof(path), "%s/%s", target_root, live_only[i]);
        char *argv[] = { (char *)"rm", (char *)"-rf", path, NULL };
        run_argv(argv); /* best-effort */
    }

    {
        /* Only the archiso/live-medium-only tooling gets stripped here;
         * nothing bootloader-related is pulled from the target by this
         * step (grub/os-prober were dropped from packages.x86_64 /
         * packages.aarch64 entirely -- systemd-boot ships as part of
         * the systemd package, which `base` already depends on, so
         * there's nothing extra to install or remove for it). */
        char *argv[] = {
            (char *)"pacman", (char *)"-Rns", (char *)"--noconfirm",
            (char *)"archiso", (char *)"mkinitcpio-archiso", (char *)"squashfs-tools",
            NULL
        };
        chroot_run(target_root, argv); /* best-effort, same as old backend */
    }

    if (cb) cb(84, "Setting up your computer to start KibaOS...", user_data);
    {
        /* KibaOS is UEFI-only, which needs /sys/firmware/efi/efivars to
         * write the NVRAM boot entry. Fail fast with a clear message
         * instead of letting bootctl die with a cryptic error. This
         * is a firmware requirement, not a VM restriction -- a VM booted
         * in UEFI mode passes this check exactly like real hardware
         * does; it's specifically legacy/BIOS boot mode that trips it,
         * which happens to be a VM's *default* in a lot of hypervisors
         * (VirtualBox, QEMU without OVMF, etc.) unless UEFI firmware is
         * explicitly selected for that VM. */
        if (access("/sys/firmware/efi", F_OK) != 0) {
            snprintf(g_finish_err, sizeof(g_finish_err),
                     "KibaOS requires UEFI boot, and this system appears to "
                     "have booted in BIOS/legacy mode. If you're installing "
                     "in a VM, check that its firmware type is set to UEFI "
                     "(not BIOS/legacy) in the hypervisor's settings, then "
                     "boot the installer again -- otherwise, this system's "
                     "firmware doesn't support UEFI at all.");
            return -1;
        }

        /* Unlike grub-install, bootctl takes no --target/arch flag --
         * systemd ships one systemd-boot*.efi per arch and bootctl always
         * installs the copy matching the binary's own arch, so this one
         * call works unmodified whether the installer binary is running
         * on x86_64 or aarch64 (no uname()-based branching needed here
         * the way grub_target required). `install` writes both the
         * generic removable-media fallback path (/boot/EFI/BOOT/) and,
         * via efibootmgr under the hood (already in
         * packages.x86_64/packages.aarch64), a real NVRAM boot entry --
         * bootctl labels that entry from /etc/os-release's PRETTY_NAME
         * (already "KibaOS", set earlier in this build) rather than a
         * generic "Linux Boot Manager", so no separate manual efibootmgr
         * call is needed the way grub-install's --bootloader-id used to
         * require. bootctl also figures out the ESP's disk and partition
         * number itself from the /boot mountpoint -- unlike the old
         * hand-rolled efibootmgr approach this replaced, it doesn't need
         * disk_path/an ESP partition number handed to it at all, so this
         * works identically whether the ESP is partition 1 (fresh
         * install) or some other number (dualboot, sharing an existing
         * ESP). --esp-path=/boot matches where the OOBE partitioner
         * already mounted the ESP (see the partitioning step earlier in
         * the install pipeline). */
        char *argv[] = {
            (char *)"bootctl", (char *)"--esp-path=/boot", (char *)"install", NULL
        };
        if (chroot_run(target_root, argv) != 0) {
            snprintf(g_finish_err, sizeof(g_finish_err), "bootctl install failed");
            return -1;
        }
    }

    if (cb) cb(86, "Building your boot menu...", user_data);
    {
        /* loader.conf: systemd-boot's own top-level config. bootctl
         * install above already wrote a stub one; overwrite it with our
         * own values rather than editing in place, since we know exactly
         * what we want and don't need to preserve anything it generated.
         * timeout 0 means boot straight to KibaOS with no visible menu,
         * same as GRUB_TIMEOUT=0 used to give us -- except on a dualboot
         * install, where a longer timeout matters for the same reason it
         * did under the old rEFInd path: systemd-boot auto-discovers
         * other EFI bootloaders already on the ESP on its own (Boot
         * Loader Specification autodetection, no os-prober equivalent
         * needed), but that discovered menu is only useful if it's
         * actually visible long enough to pick from. */
        snprintf(path, sizeof(path), "%s/boot/loader/loader.conf", target_root);
        char loader_conf[256];
        snprintf(loader_conf, sizeof(loader_conf),
                 "default kibaos.conf\n"
                 "timeout %d\n"
                 "console-mode max\n"
                 "editor no\n",
                 dualboot ? 5 : 0);
        if (write_file(path, loader_conf) != 0) {
            snprintf(g_finish_err, sizeof(g_finish_err), "writing loader.conf failed");
            return -1;
        }

        /* kibaos.conf: the actual boot entry (Boot Loader Specification
         * Type #1 -- a plain text file, not a UKI). bootctl install
         * already created /boot/loader/entries/ for us. Unlike GRUB's
         * grub-mkconfig, this file never needs regenerating on a kernel
         * update: vmlinuz-linux/initramfs-linux.img are the same fixed
         * names on every boot (the copy step earlier in kiba_install()
         * normalizes both x86_64's "linux" and ALARM's "linux-aarch64"
         * packages down to those names), and the `linux` package's own
         * pacman hooks keep initramfs-linux.img refreshed in place on
         * future kernel updates -- so this gets written once, here, and
         * never touched again. root=UUID=... is written directly from
         * root_uuid (resolved by the caller from the freshly-formatted
         * filesystem) rather than relying on any auto-generation, the
         * same reasoning the old rEFInd path used to avoid picking up
         * kernel parameters from the live/chroot environment instead of
         * the target system. */
        snprintf(path, sizeof(path), "%s/boot/loader/entries", target_root);
        mkdir(path, 0755); /* best-effort, bootctl install already made this */

        snprintf(path, sizeof(path), "%s/boot/loader/entries/kibaos.conf", target_root);
        char entry[1024];
        snprintf(entry, sizeof(entry),
                 "title KibaOS\n"
                 "linux /vmlinuz-linux\n"
                 "initrd /initramfs-linux.img\n"
                 "options root=UUID=%s rw quiet splash loglevel=3 "
                 "rd.udev.log_level=3 vt.global_cursor_default=0 "
                 "plymouth.use-simpledrm=1 "
                 "lsm=landlock,lockdown,yama,integrity,apparmor,bpf\n",
                 root_uuid);
        if (write_file(path, entry) != 0) {
            snprintf(g_finish_err, sizeof(g_finish_err), "writing boot entry failed");
            return -1;
        }
    }

    (void)disk_path;   /* no longer needed -- bootctl resolves the ESP's disk from the /boot mountpoint itself */
    (void)root_partno; /* no longer needed -- bootctl resolves the ESP's partition number the same way */

    if (cb) cb(88, "Turning on background features...", user_data);
    {
        /* `systemctl enable gdm` below only wires up the
         * display-manager.service alias -- it does NOT change
         * default.target. A stock pacstrap install leaves default.target
         * at multi-user.target, so without this explicit set-default the
         * freshly installed system boots straight to a text-mode login
         * prompt on first boot instead of GDM's graphical login screen. */
        char *argv_target[] = {
            (char *)"systemctl", (char *)"set-default", (char *)"graphical.target", NULL
        };
        if (chroot_run(target_root, argv_target) != 0) {
            snprintf(g_finish_err, sizeof(g_finish_err), "systemctl set-default graphical.target failed");
            return -1;
        }

        static const char *services[] = {
            "NetworkManager", "gdm", "bluetooth",
            "systemd-timesyncd", "systemd-time-wait-sync", "kibaos-panelfix",
            /* systemd-bless-boot.service / systemd-boot-check-no-failures.
             * service are gone -- those manage systemd-boot's optional
             * tries-left/tries-done boot-counting suffix on an entry's
             * filename (e.g. kibaos+3-0.conf), which only kicks in if
             * the entry file is named with a counter to begin with.
             * kibaos.conf (written above) deliberately isn't, so there's
             * nothing for these services to track -- same effective
             * behavior as under GRUB, just for a different reason. */
        };
        for (size_t i = 0; i < sizeof(services)/sizeof(services[0]); i++) {
            char *argv[] = { (char *)"systemctl", (char *)"enable", (char *)services[i], NULL };
            chroot_run(target_root, argv); /* best-effort */
        }
    }

    if (cb) cb(89, "Saving your Wi-Fi settings...", user_data);
    {
        /* arch-chroot shares the host's network namespace, so the live
         * session's own connection is already what pacman used above and
         * below -- this copy isn't for that. It's so the INSTALLED system
         * comes up already connected on first boot instead of making
         * someone re-enter the Wi-Fi password they just typed into OOBE
         * two minutes ago. NetworkManager refuses to load a connection
         * profile unless it's mode 600 owned by root, so that's set
         * explicitly rather than trusting whatever the live session left
         * them as. */
        snprintf(path, sizeof(path), "%s/etc/NetworkManager/system-connections", target_root);
        mkdir(path, 0700);

        char *argv[] = {
            (char *)"bash", (char *)"-c",
            (char *)"cp -a /etc/NetworkManager/system-connections/. \"$1\"/ 2>/dev/null; "
                    "chown -R root:root \"$1\"; find \"$1\" -type f -exec chmod 600 {} +",
            (char *)"--", path, NULL
        };
        run_argv(argv); /* best-effort -- fine if the live session never had a saved connection */
    }

    if (cb) cb(90, "Adding support for videos and music...", user_data);
    {
        /* gst-plugins-ugly, gst-libav, and ffmpeg cover the actually
         * patent-encumbered codecs (h264, mp3, aac, etc.) -- deliberately
         * left out of packages.x86_64 so the ISO itself never carries
         * them, and pulled here instead, straight onto the disk being
         * installed to. This needs a live network connection on the
         * install machine; if there isn't one, pacman just fails and we
         * carry on -- Totem still plays the royalty-free formats gst-
         * plugins-good/-bad already cover from the ISO packages, and the
         * user can pull these later from Settings/pacman once online. */
        char *argv[] = {
            (char *)"pacman", (char *)"-S", (char *)"--noconfirm", (char *)"--needed",
            (char *)"gst-plugins-ugly", (char *)"gst-libav", (char *)"ffmpeg", NULL
        };
        if (chroot_run(target_root, argv) != 0 && cb) {
            cb(90, "Couldn't add video/music support right now (no internet?) -- "
                   "you can add it later from Settings",
               user_data);
        }
    }

    if (cb) cb(91, "Adding your startup screen...", user_data);
    snprintf(path, sizeof(path), "%s/etc/sysctl.d", target_root);
    mkdir(path, 0755);
    snprintf(path, sizeof(path), "%s/etc/sysctl.d/20-quiet-printk.conf", target_root);
    /* Belt-and-suspenders for silent boot: loglevel=3 on the kernel cmdline
     * only filters what reaches the console at the level it's set; this
     * sysctl additionally caps the kernel's own default console log level,
     * catching messages cmdline filtering alone sometimes misses. */
    write_file(path, "kernel.printk = 3 3 3 3\n");

    snprintf(path, sizeof(path), "%s/etc/plymouth", target_root);
    mkdir(path, 0755);
    snprintf(path, sizeof(path), "%s/etc/plymouth/plymouthd.conf", target_root);
    write_file(path, "[Daemon]\nTheme=kibaos\nShowDelay=0\nDeviceTimeout=8\n");
    {
        /* Sanity-check the theme actually landed in target_root before we
         * try to switch to it -- if the airootfs->target copy ever misses
         * it, this turns a silent "boot shows the stock theme" bug into a
         * clear, logged failure instead. */
        char theme_check[1024];
        snprintf(theme_check, sizeof(theme_check), "%s/usr/share/plymouth/themes/kibaos/kibaos.plymouth", target_root);
        struct stat st;
        if (stat(theme_check, &st) != 0) {
            if (cb) cb(93, "Couldn't find the KibaOS startup screen -- using the default one instead", user_data);
        } else {
            char *argv[] = { (char *)"plymouth-set-default-theme", (char *)"kibaos", NULL };
            if (chroot_run(target_root, argv) != 0) {
                /* Non-fatal: a missing splash theme shouldn't abort the
                 * whole install, but MUST be visible, or the initramfs
                 * rebuild below will silently bake in whatever theme was
                 * already active (the stock default) instead of kibaos --
                 * this was previously discarded with no error or log line. */
                if (cb) cb(93, "Couldn't set the KibaOS startup screen -- using the default one instead", user_data);
            }
        }
    }

    if (cb) cb(94, "Finishing up...", user_data);
    {
        /* mkinitcpio with no -k falls back to `uname -r` -- which, inside
         * a chroot, is still the LIVE ENVIRONMENT's running kernel version,
         * not whatever the `linux` package pacman just pulled into
         * target_root. chroot() only changes the filesystem root; uname()
         * is answered by the actual running kernel regardless. With
         * kiba-kernel this was a non-issue (same exact package/version
         * baked into both the ISO and the install target, always). Stock
         * `linux` from pacman removes that guarantee -- if the live ISO's
         * kernel and the freshly-installed one ever drift, mkinitcpio
         * silently builds against a /usr/lib/modules/<wrong-version>/
         * that doesn't exist in target_root, producing an initramfs with
         * no real modules in it (no root fs driver, no block layer) --
         * which is exactly what an emergency-shell-on-first-boot looks
         * like. Read the actual installed kernel version out of
         * target_root's own /usr/lib/modules instead of trusting ambient
         * uname -r, and pass it explicitly via -k. */
        char kver[256] = {0};
        {
            char modpath[1024];
            snprintf(modpath, sizeof(modpath), "%s/usr/lib/modules", target_root);
            DIR *d = opendir(modpath);
            if (d) {
                struct dirent *ent;
                while ((ent = readdir(d)) != NULL) {
                    if (ent->d_name[0] == '.') continue;
                    char full[1200];
                    snprintf(full, sizeof(full), "%s/%s", modpath, ent->d_name);
                    struct stat st;
                    if (stat(full, &st) == 0 && S_ISDIR(st.st_mode)) {
                        snprintf(kver, sizeof(kver), "%s", ent->d_name);
                        break; /* stock `linux` ships exactly one versioned dir here */
                    }
                }
                closedir(d);
            }
        }
        if (kver[0] == '\0') {
            snprintf(g_finish_err, sizeof(g_finish_err),
                     "couldn't find an installed kernel under /usr/lib/modules");
            return -1;
        }

        char *argv[] = {
            (char *)"mkinitcpio", (char *)"-c", (char *)"/etc/mkinitcpio.conf.d/installed.conf",
            (char *)"-g", (char *)"/boot/initramfs-linux.img",
            (char *)"-k", kver, NULL
        };
        if (chroot_run(target_root, argv) != 0) {
            snprintf(g_finish_err, sizeof(g_finish_err), "mkinitcpio failed");
            return -1;
        }
    }

    snprintf(path, sizeof(path), "%s/etc/sudoers.d/wheel", target_root);
    write_file(path, "%wheel ALL=(ALL:ALL) ALL\n");
    chmod(path, 0440);

    (void)root_part; /* kept for signature symmetry / future use */
    return 0;
}
